[env]
# WINIT_UNIX_BACKENED = x11
# TERM = "xterm-256color"
http_proxy = "http://127.0.0.1:7897"
https_proxy = "http://127.0.0.1:7897"

[window]
# 这个是将标题栏隐藏
decorations = "buttonless"
# 这两个控制的是文本的内容和窗口边缘的距离
padding.x = 10
padding.y = 10

dynamic_padding = false

# 这个是不透明度
opacity = 0.7
# 这是是毛玻璃，或者叫磨砂
# blur = true
# 这个调整的是打开的时候的窗口大小
dimensions.columns = 120
dimensions.lines = 39
# 这个配置是用于macos 中的，将 option 当作alt，
# 如果是linux 的话，是没有这个问题的
# option_as_alt = "Both"
# dpi = 192


[font]
# 这个是字体的设置
normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"
size = 12
# 说实话，我也不是很确定这个配置是干什么用的
builtin_box_drawing = true

[scrolling]
# 这里控制的是最大的scrollback 行数，当然是越多越好了，不差这点空间
history = 100000
# 每次向上滚动鼠标的时候会移动多少行
multiplier = 3


[terminal]
# 可以复制粘贴了
osc52 = "CopyPaste"

[cursor]
style.shape = "Block"
# style.shape = "Beam"
style.blinking = "On"

[keyboard]
bindings = [{key="F11",action="ToggleFullscreen"},
            {key="n", mods="Control|Shift", action="CreateNewWindow"},
]


[colors.normal]
green = '#31748f'
[colors.bright]
green = '#31748f'

# [colors.hints]
# start = {foreground = '#908caa', background = '#1f1d2e' }
# end = { foreground = '#6e6a86', background = '#1f1d2e' }
#

[colors.primary]
background = '#000000'
foreground = '#FFFFFF'


[general]


# 实时重载配置文件，不用重启测试配置选项
live_config_reload = true

